title = "New Beginnings"
date = "2015-05-28"                                                                                                                                                         # T22:40:32.169Z
description = "This is a custom description for SEO and Open Graph purposes, rather than the default generated excerpt. Simply add a description field to the frontmatter."
image_url = "images/rust-chains.jpeg"
